import Link from "next/link";
import { getDestinationsTree } from "@/lib/api";

const TRUST_BADGES = [
  "5-Star Guides",
  "Outstanding Memories at the Best Price",
  "Free Cancellation with Refund",
];

export default async function HomePage() {
  const tree = await getDestinationsTree();
  const countries = tree?.countries ?? [];

  return (
    <div>
      <section className="bg-gradient-to-br from-brand-navy to-brand-primary-dark py-16 text-white">
        <div className="mx-auto max-w-6xl px-6">
          <h1 className="max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">
            Explore the world in a dream way
          </h1>
          <p className="mt-4 max-w-xl text-white/80">
            Every page below is generated by the Rosotravel AI decision engine: it shortlists
            winners from raw inventory, explains why they were picked, and publishes schema.org
            markup for search and LLM discovery.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            {TRUST_BADGES.map((badge) => (
              <span
                key={badge}
                className="rounded-full bg-white/10 px-4 py-2 text-sm font-medium backdrop-blur"
              >
                {badge}
              </span>
            ))}
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="mb-6 flex items-end justify-between gap-4">
          <div>
            <h2 className="text-2xl font-semibold text-brand-navy">Choose a country</h2>
            <p className="mt-1 text-sm text-slate-600">
              Country pages group the city hubs underneath them, so travelers move from country
              discovery into city-level decisions.
            </p>
          </div>
        </div>

        {countries.length === 0 ? (
          <p className="text-sm text-slate-500">No countries published yet.</p>
        ) : (
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {countries.map((country) => (
              <Link
                key={country.entity_id}
                href={`/country/${country.slug}`}
                className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
              >
                <div className="flex h-32 items-center justify-center bg-gradient-to-br from-brand-primary to-brand-primary-dark px-4 text-center text-xl font-semibold text-white">
                  {country.name}
                </div>
                <div className="p-4">
                  <p className="font-medium text-brand-navy group-hover:text-brand-primary">
                    {country.name}
                  </p>
                  <p className="mt-1 text-sm text-slate-500">{country.cities.length} city hubs</p>
                  <div className="mt-3 flex flex-wrap gap-1">
                    {country.cities.slice(0, 3).map((city) => (
                      <span
                        key={city.entity_id}
                        className="rounded bg-slate-100 px-2 py-0.5 text-xs text-slate-600"
                      >
                        {city.name}
                      </span>
                    ))}
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
